services:
  - type: web
    name: vnm-gnm-solar-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview

    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: vnm-gnm-solar-backend
          envVarKey: RENDER_EXTERNAL_URL
        value: ${RENDER_EXTERNAL_URL}/api

  - type: web
    name: vnm-gnm-solar-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: vnm-gnm-solar-frontend
          envVarKey: RENDER_EXTERNAL_URL
        value: ${RENDER_EXTERNAL_URL}
