services:
  - type: web
    name: vnm-gnm-ocr
    runtime: docker
    dockerfilePath: ./Dockerfile
    port: 5001
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/4.00/tessdata
